apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
  namespace: voting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-app
  template:
    metadata:
      labels:
        app: result-app
    spec:
      containers:
      - name: result-app
        image: perdita997/result-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_DB
          value: votedb
        - name: POSTGRES_USER
          value: uservote
        - name: POSTGRES_PASSWORD
          value: userpass

