name: Docker CI & Deploy to Kind

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push vote-app
        uses: docker/build-push-action@v5
        with:
          context: ./vote-app
          push: true
          tags: perdita997/vote-app:latest

      - name: Build & Push worker
        uses: docker/build-push-action@v5
        with:
          context: ./worker
          push: true
          tags: perdita997/worker:latest

      - name: Build & Push result-app
        uses: docker/build-push-action@v5
        with:
          context: ./result-app
          push: true
          tags: perdita997/result-app:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Install kind and kubectl
      - name: Set up Kind and kubectl
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # Create a Kind cluster
      - name: Create Kind cluster
        run: |
          kind create cluster --name voting-cluster

      # Verify cluster
      - name: Verify Kind cluster
        run: kubectl get nodes

      # Load Docker images into Kind
      - name: Load Docker images into Kind
        run: |
          kind load docker-image perdita997/vote-app:latest --name voting-cluster
          kind load docker-image perdita997/worker:latest --name voting-cluster
          kind load docker-image perdita997/result-app:latest --name voting-cluster

      # Deploy Kubernetes manifests
      - name: Deploy manifests
        run: |
          kubectl apply -f infra/k8s/namespace.yaml
          kubectl apply -n voting -f infra/k8s/

